# Generated by Django 5.2.6 on 2025-10-16 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('sumo_rc', 'Sumo RC'), ('sumo_autonomo', 'Sumo Autónomo'), ('barcos', 'Barcos RC'), ('futbol', 'Fútbol RC')], max_length=20)),
                ('nombre', models.CharField(default='Torneo', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='FootballGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('completed', models.BooleanField(default=False)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='football_groups', to='jurados.tournament')),
            ],
            options={
                'ordering': ['codigo'],
                'unique_together': {('tournament', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='jurados.tournament')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('tournament', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='FootballTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pj', models.IntegerField(default=0)),
                ('g', models.IntegerField(default=0)),
                ('e', models.IntegerField(default=0)),
                ('p', models.IntegerField(default=0)),
                ('gf', models.IntegerField(default=0)),
                ('gc', models.IntegerField(default=0)),
                ('dg', models.IntegerField(default=0)),
                ('pts', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='jurados.footballgroup')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jurados.tournamentparticipant')),
            ],
            options={
                'ordering': ['-pts', '-dg', '-gf', 'participant__nombre'],
                'unique_together': {('group', 'participant')},
            },
        ),
        migrations.CreateModel(
            name='TournamentRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=0)),
                ('nombre', models.CharField(max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='jurados.tournament')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bye', models.BooleanField(default=False)),
                ('a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_as_a', to='jurados.tournamentparticipant')),
                ('b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_as_b', to='jurados.tournamentparticipant')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_wins', to='jurados.tournamentparticipant')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='jurados.tournamentround')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FootballGroupMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_home', models.IntegerField(blank=True, null=True)),
                ('goals_away', models.IntegerField(blank=True, null=True)),
                ('played', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='jurados.footballgroup')),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='jurados.footballteam')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='jurados.footballteam')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('group', 'home', 'away')},
            },
        ),
    ]
