# Generated by Django 5.2.6 on 2025-10-20 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurados', '0002_tournament_footballgroup_tournamentparticipant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='categoria',
            field=models.CharField(choices=[('sumo_rc', 'Sumo RC'), ('sumo_autonomo', 'Sumo Autónomo'), ('barcos', 'Barcos RC'), ('futbol', 'Fútbol RC'), ('rally', 'Rally')], max_length=20),
        ),
        migrations.CreateModel(
            name='RallyTriad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=0)),
                ('a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rally_triad_a', to='jurados.tournamentparticipant')),
                ('b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rally_triad_b', to='jurados.tournamentparticipant')),
                ('c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rally_triad_c', to='jurados.tournamentparticipant')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rally_triads', to='jurados.tournament')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rally_triad_winner', to='jurados.tournamentparticipant')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
